### ISSUE TITLE
lto1: fatal error: bytecode stream in file ‘/usr/lib/x86_64-linux-gnu/libbenchmark_main.a’ generated with LTO version 11.2 instead of the expected 11.3

### ISSUE THREAD

**Issue by Kaju-Bubanja** [ros2/performance_test_fixture#22]
When I try to compile my workspace I get following stacktrace on a clean install, no build folder, on an up to date Ubuntu22 using ros2 rolling.

```
--- stderr: performance_test_fixture                                                                                                                                         
lto1: fatal error: bytecode stream in file ‘/usr/lib/x86_64-linux-gnu/libbenchmark_main.a’ generated with LTO version 11.2 instead of the expected 11.3
compilation terminated.
lto-wrapper: fatal error: /usr/bin/c++ returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/benchmark_malloc_realloc_no_memory_tools.dir/build.make:99: benchmark_malloc_realloc_no_memory_tools] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:195: CMakeFiles/benchmark_malloc_realloc_no_memory_tools.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
lto1: fatal error: bytecode stream in file ‘/usr/lib/x86_64-linux-gnu/libbenchmark_main.a’ generated with LTO version 11.2 instead of the expected 11.3
compilation terminated.
lto-wrapper: fatal error: /usr/bin/c++ returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/benchmark_malloc_realloc.dir/build.make:101: benchmark_malloc_realloc] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:169: CMakeFiles/benchmark_malloc_realloc.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< performance_test_fixture [4.24s, exited with code 2]
```

How can I fix this issue?

**Comment by clalancette** [comment]
So one issue here is that the build should not be using `/usr/lib/x86_64-linux-gnu/libbenchmark_main.a`; it should always be using the `.so` here.  It's a packaging bug in Ubuntu, but our vendor package detects the situation and works around it.

Can you give us more information about both your platform (which exact Ubuntu version) and your workspace setup (`vcs export --exact`)?  That should help us triage this more.

**Comment by Kaju-Bubanja** [comment]
Being frustrated by various compiling problems in rolling I went back to humble. It was any ways time because of the project cycle, it was nice being on the cutting edge of ros for a while, but for now I enjoy the hassle free easily buildable humble distro. So unfortunately I can't reproduce this anymore, since I deleted my rolling workspace.

**Comment by alecGraves** [comment]
I am getting this error when doing a clean humble build.

```
--- stderr: performance_test_fixture
lto1: fatal error: bytecode stream in file ‘/usr/lib/x86_64-linux-gnu/libbenchmark_main.a’ generated with LTO version 11.2 instead of the expected 11.3
compilation terminated.
lto-wrapper: fatal error: /usr/bin/c++ returned 1 exit status
compilation terminated.
```

[(vcs export here)](https://paste.sr.ht/~alecgraves/e32d54fa099a5a780b378004092d1bf0c9f70a9a)

```
$ uname -a
Linux midnight 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

**Comment by alecGraves** [comment]
Workaround: build libbenchmark from source until ubuntu devs can unscrew this.

#### 1. enable debian source downloads 
go to `/etc/apt/sources.list.d` and uncomment all of the deb-src

then,

    sudo apt-get update


#### 2.  Download the sources and install
Make an empty folder
```
mkdir benchmark
cd benchmark
echo > COLCON_IGNORE
```
Download libbenchmark sources:
```
apt-get source libbenchmark-dev
```

go into the downloaded folder:
```
cd benchmark-1.6.1/
```
 install any missing deps. You might need to build a couple times to find them all:
```
sudo apt install debhelper-compat libgmock-dev
```
build:
```
dpkg-buildpackage
```
go back to the benchmakr folder. If the build worked, you should see your debs.
```
cd ..
ls
```
install your homemade deps
```
sudo dpkg -i ./*.deb
```

If that does not work, let me know and I will try to fix these instructions.

**Comment by 1f-small-Xue-study-today** [comment]
ruize@ruize-SuperPC:~/benchmark$ apt-get source libbenchmark-dev
Reading package lists... Done
Picking 'benchmark' as source package instead of 'libbenchmark-dev'
NOTICE: 'benchmark' packaging is maintained in the 'Git' version control system at:
https://salsa.debian.org/science-team/benchmark.git
Please use:
git clone https://salsa.debian.org/science-team/benchmark.git
to retrieve the latest (possibly unreleased) updates to the package.
Skipping already downloaded file 'benchmark_1.5.0-4build1.dsc'
Skipping already downloaded file 'benchmark_1.5.0.orig.tar.gz'
Skipping already downloaded file 'benchmark_1.5.0-4build1.debian.tar.xz'
Need to get 0 B of source archives.
Skipping unpack of already unpacked source in benchmark-1.5.0
ruize@ruize-SuperPC:~/benchmark$ ls
COLCON_IGNORE  benchmark-1.5.0  benchmark_1.5.0-4build1.debian.tar.xz  benchmark_1.5.0-4build1.dsc  benchmark_1.5.0.orig.tar.gz


but, I cannot source a 1.6x version?!
